# dbt_project.yml
name: 'my_project'
version: '1.0'
config-version: 2

vars:
  dev:
    my_var: 'value_for_dev'
    another_var: 'dev_setting'
    source:
      database: "dev_database"
      schema: "dev_schema"
      table: "dev_table"
  prod:
    my_var: 'value_for_prod'
    another_var: 'prod_setting'
    source:
      database: "prod_database"
      schema: "prod_schema"
      table: "prod_table"